// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalBot.Data;

#nullable disable

namespace PersonalBot.Data.Migrations;

[DbContext(typeof(BotDbContext))]
[Migration("20260612233630_WebhookCreatedAt")]
partial class _20260612233630_WebhookCreatedAt
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

        modelBuilder.Entity("PersonalBot.Data.Models.AiTask", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Agent")
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("IssueNum")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("Phase")
                    .HasColumnType("INTEGER");

                b.Property<string>("Prompt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("RepoPath")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("RetryCount")
                    .HasColumnType("INTEGER");

                b.Property<string>("Session")
                    .HasColumnType("TEXT");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("AiTasks");
            });

        modelBuilder.Entity("PersonalBot.Data.Models.GitHubWebhook", b =>
            {
                b.Property<string>("DeliveryId")
                    .HasColumnType("TEXT");

                b.Property<string>("Action")
                    .HasColumnType("TEXT");

                b.Property<string>("CloneUrl")
                    .HasColumnType("TEXT");

                b.Property<string>("CommentBody")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("EventType")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("HeadRef")
                    .HasColumnType("TEXT");

                b.Property<bool>("IsProcessed")
                    .HasColumnType("INTEGER");

                b.Property<string>("IssueBody")
                    .HasColumnType("TEXT");

                b.Property<string>("IssueNumber")
                    .HasColumnType("TEXT");

                b.Property<string>("IssueTitle")
                    .HasColumnType("TEXT");

                b.Property<bool>("PrMerged")
                    .HasColumnType("INTEGER");

                b.Property<string>("RawBody")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("ReactionContent")
                    .HasColumnType("TEXT");

                b.Property<string>("RepoName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("DeliveryId");

                b.ToTable("Webhooks");
            });
#pragma warning restore 612, 618
    }
}
