// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalBot.Data;

#nullable disable

namespace PersonalBot.Data.Migrations;

[DbContext(typeof(BotDbContext))]
[Migration("20260628185042_NewSessionFormat")]
partial class _20260628185042_NewSessionFormat
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

        modelBuilder.Entity("PersonalBot.Data.Models.Workflows.Workflow", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Discriminator")
                    .IsRequired()
                    .HasMaxLength(21)
                    .HasColumnType("TEXT");

                b.Property<string>("Output")
                    .HasColumnType("TEXT");

                b.Property<Guid?>("ParentWorkflowId")
                    .HasColumnType("TEXT");

                b.Property<int>("RetryCount")
                    .HasColumnType("INTEGER");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("ParentWorkflowId");

                b.ToTable("Workflows");

                b.HasDiscriminator<string>("Discriminator").HasValue("Workflow");

                b.UseTphMappingStrategy();
            });

        modelBuilder.Entity("PersonalBot.Data.Models.Workflows.ChatIssueReply", b =>
            {
                b.HasBaseType("PersonalBot.Data.Models.Workflows.Workflow");

                b.HasDiscriminator().HasValue("ChatIssueReply");
            });

        modelBuilder.Entity("PersonalBot.Data.Models.Workflows.ChatStarted", b =>
            {
                b.HasBaseType("PersonalBot.Data.Models.Workflows.Workflow");

                b.Property<int>("AgentPhase")
                    .HasColumnType("INTEGER")
                    .HasColumnName("AgentPhase");

                b.Property<string>("ArtifactOutput")
                    .HasColumnType("TEXT")
                    .HasColumnName("ArtifactOutput");

                b.Property<string>("ChatOutput")
                    .HasColumnType("TEXT")
                    .HasColumnName("ChatOutput");

                b.Property<string>("IssueNumber")
                    .IsRequired()
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("IssueNumber");

                b.Property<string>("Prompt")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("Prompt");

                b.Property<string>("RepoName")
                    .IsRequired()
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("RepoName");

                b.ComplexProperty(typeof(Dictionary<string, object>), "Session", "PersonalBot.Data.Models.Workflows.ChatStarted.Session#Session", b1 =>
                    {
                        b1.Property<string>("AgentName")
                            .IsRequired();

                        b1.Property<string>("ConversationId");

                        b1.Property<string>("SerializedAgentSession");

                        b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "Messages", "PersonalBot.Data.Models.Workflows.ChatStarted.Session#Session.Messages#AgentMessage", b2 =>
                            {
                                b2.IsRequired();

                                b2.Property<string>("Message")
                                    .IsRequired();

                                b2.Property<int>("Type");
                            });

                        b1
                            .ToJson("Session")
                            .HasColumnType("TEXT");
                    });

                b.HasDiscriminator().HasValue("ChatStarted");
            });

        modelBuilder.Entity("PersonalBot.Data.Models.Workflows.IssueCommentCreated", b =>
            {
                b.HasBaseType("PersonalBot.Data.Models.Workflows.Workflow");

                b.Property<string>("CloneUrl")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("CloneUrl");

                b.Property<string>("CommentBody")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("CommentBody");

                b.Property<string>("IssueNumber")
                    .IsRequired()
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("IssueNumber");

                b.Property<string>("RepoName")
                    .IsRequired()
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("RepoName");

                b.HasDiscriminator().HasValue("IssueCommentCreated");
            });

        modelBuilder.Entity("PersonalBot.Data.Models.Workflows.IssueOpened", b =>
            {
                b.HasBaseType("PersonalBot.Data.Models.Workflows.Workflow");

                b.Property<string>("CloneUrl")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("CloneUrl");

                b.Property<string>("IssueBody")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("IssueBody");

                b.Property<string>("IssueNumber")
                    .IsRequired()
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("IssueNumber");

                b.Property<string>("IssueTitle")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("IssueTitle");

                b.Property<string>("RepoName")
                    .IsRequired()
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("RepoName");

                b.HasDiscriminator().HasValue("IssueOpened");
            });

        modelBuilder.Entity("PersonalBot.Data.Models.Workflows.PullRequestClosed", b =>
            {
                b.HasBaseType("PersonalBot.Data.Models.Workflows.Workflow");

                b.Property<string>("HeadRef")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("HeadRef");

                b.Property<bool>("PrMerged")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("INTEGER")
                    .HasColumnName("PrMerged");

                b.Property<string>("RepoName")
                    .IsRequired()
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("RepoName");

                b.HasDiscriminator().HasValue("PullRequestClosed");
            });

        modelBuilder.Entity("PersonalBot.Data.Models.Workflows.ReactionCreated", b =>
            {
                b.HasBaseType("PersonalBot.Data.Models.Workflows.Workflow");

                b.Property<string>("CloneUrl")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("CloneUrl");

                b.Property<string>("IssueNumber")
                    .IsRequired()
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("IssueNumber");

                b.Property<string>("ReactionContent")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("ReactionContent");

                b.Property<string>("RepoName")
                    .IsRequired()
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("RepoName");

                b.HasDiscriminator().HasValue("ReactionCreated");
            });

        modelBuilder.Entity("PersonalBot.Data.Models.Workflows.TaskApproved", b =>
            {
                b.HasBaseType("PersonalBot.Data.Models.Workflows.Workflow");

                b.Property<string>("IssueNumber")
                    .IsRequired()
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("IssueNumber");

                b.Property<string>("RepoName")
                    .IsRequired()
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("RepoName");

                b.HasDiscriminator().HasValue("TaskApproved");
            });

        modelBuilder.Entity("PersonalBot.Data.Models.Workflows.WebhookReceived", b =>
            {
                b.HasBaseType("PersonalBot.Data.Models.Workflows.Workflow");

                b.Property<string>("Action")
                    .HasColumnType("TEXT");

                b.Property<string>("CloneUrl")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("CloneUrl");

                b.Property<string>("CommentBody")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("CommentBody");

                b.Property<string>("DeliveryId")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("DeliveryId");

                b.Property<string>("EventType")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("EventType");

                b.Property<string>("HeadRef")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("HeadRef");

                b.Property<string>("IssueBody")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("IssueBody");

                b.Property<string>("IssueNumber")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("IssueNumber");

                b.Property<string>("IssueTitle")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("IssueTitle");

                b.Property<bool>("PrMerged")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("INTEGER")
                    .HasColumnName("PrMerged");

                b.Property<string>("RawBody")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("RawBody");

                b.Property<string>("ReactionContent")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("ReactionContent");

                b.Property<string>("RepoName")
                    .IsRequired()
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("RepoName");

                b.HasDiscriminator().HasValue("WebhookReceived");
            });

        modelBuilder.Entity("PersonalBot.Data.Models.Workflows.Workflow", b =>
            {
                b.HasOne("PersonalBot.Data.Models.Workflows.Workflow", "ParentWorkflow")
                    .WithMany("ChildWorkflows")
                    .HasForeignKey("ParentWorkflowId");

                b.Navigation("ParentWorkflow");
            });

        modelBuilder.Entity("PersonalBot.Data.Models.Workflows.Workflow", b =>
            {
                b.Navigation("ChildWorkflows");
            });
#pragma warning restore 612, 618
    }
}
