// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalBot.Data;

#nullable disable

namespace PersonalBot.Data.Migrations;

[DbContext(typeof(BotDbContext))]
[Migration("20260613222850_InitialMigration")]
partial class _20260613222850_InitialMigration
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

        modelBuilder.Entity("PersonalBot.Data.Models.AiTask", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Agent")
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("IssueNum")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("Phase")
                    .HasColumnType("INTEGER");

                b.Property<string>("Prompt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("RepoPath")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("RetryCount")
                    .HasColumnType("INTEGER");

                b.Property<string>("Session")
                    .HasColumnType("TEXT");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("AiTasks");
            });

        modelBuilder.Entity("PersonalBot.Data.Models.GitHubWebhook", b =>
            {
                b.Property<string>("DeliveryId")
                    .HasColumnType("TEXT");

                b.Property<string>("Action")
                    .HasColumnType("TEXT");

                b.Property<string>("CloneUrl")
                    .HasColumnType("TEXT");

                b.Property<string>("CommentBody")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("EventType")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("HeadRef")
                    .HasColumnType("TEXT");

                b.Property<string>("IssueBody")
                    .HasColumnType("TEXT");

                b.Property<string>("IssueNumber")
                    .HasColumnType("TEXT");

                b.Property<string>("IssueTitle")
                    .HasColumnType("TEXT");

                b.Property<bool>("PrMerged")
                    .HasColumnType("INTEGER");

                b.Property<string>("RawBody")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("ReactionContent")
                    .HasColumnType("TEXT");

                b.Property<string>("RepoName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER");

                b.HasKey("DeliveryId");

                b.ToTable("Webhooks");
            });

        modelBuilder.Entity("PersonalBot.Data.Models.Workflows.Workflow", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Discriminator")
                    .IsRequired()
                    .HasMaxLength(21)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Workflows");

                b.HasDiscriminator<string>("Discriminator").HasValue("Workflow");

                b.UseTphMappingStrategy();
            });

        modelBuilder.Entity("PersonalBot.Data.Models.Workflows.IssueCommentCreated", b =>
            {
                b.HasBaseType("PersonalBot.Data.Models.Workflows.Workflow");

                b.Property<string>("CloneUrl")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("CloneUrl");

                b.Property<string>("CommentBody")
                    .HasColumnType("TEXT")
                    .HasColumnName("CommentBody");

                b.Property<string>("IssueNumber")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("IssueNumber");

                b.Property<string>("RepoName")
                    .IsRequired()
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("RepoName");

                b.HasDiscriminator().HasValue("IssueCommentCreated");
            });

        modelBuilder.Entity("PersonalBot.Data.Models.Workflows.IssueOpened", b =>
            {
                b.HasBaseType("PersonalBot.Data.Models.Workflows.Workflow");

                b.Property<string>("CloneUrl")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("CloneUrl");

                b.Property<string>("IssueBody")
                    .HasColumnType("TEXT")
                    .HasColumnName("IssueBody");

                b.Property<string>("IssueNumber")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("IssueNumber");

                b.Property<string>("IssueTitle")
                    .HasColumnType("TEXT")
                    .HasColumnName("IssueTitle");

                b.Property<string>("RepoName")
                    .IsRequired()
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("RepoName");

                b.HasDiscriminator().HasValue("IssueOpened");
            });

        modelBuilder.Entity("PersonalBot.Data.Models.Workflows.PullRequestClosed", b =>
            {
                b.HasBaseType("PersonalBot.Data.Models.Workflows.Workflow");

                b.Property<string>("HeadRef")
                    .HasColumnType("TEXT")
                    .HasColumnName("HeadRef");

                b.Property<bool>("PrMerged")
                    .HasColumnType("INTEGER")
                    .HasColumnName("PrMerged");

                b.Property<string>("RepoName")
                    .IsRequired()
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("RepoName");

                b.HasDiscriminator().HasValue("PullRequestClosed");
            });

        modelBuilder.Entity("PersonalBot.Data.Models.Workflows.ReactionCreated", b =>
            {
                b.HasBaseType("PersonalBot.Data.Models.Workflows.Workflow");

                b.Property<string>("CloneUrl")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("CloneUrl");

                b.Property<string>("IssueNumber")
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("IssueNumber");

                b.Property<string>("ReactionContent")
                    .HasColumnType("TEXT")
                    .HasColumnName("ReactionContent");

                b.Property<string>("RepoName")
                    .IsRequired()
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("RepoName");

                b.HasDiscriminator().HasValue("ReactionCreated");
            });

        modelBuilder.Entity("PersonalBot.Data.Models.Workflows.TaskApproved", b =>
            {
                b.HasBaseType("PersonalBot.Data.Models.Workflows.Workflow");

                b.Property<string>("IssueNumber")
                    .IsRequired()
                    .ValueGeneratedOnUpdateSometimes()
                    .HasColumnType("TEXT")
                    .HasColumnName("IssueNumber");

                b.Property<string>("RepoPath")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("RepoPath");

                b.Property<string>("SessionId")
                    .HasColumnType("TEXT")
                    .HasColumnName("SessionId");

                b.HasDiscriminator().HasValue("TaskApproved");
            });
#pragma warning restore 612, 618
    }
}
